#!/bin/bash

MYDIR=$(cd -P -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source ${MYDIR}/settings.sh

echo "  - Cleaning up old artifacts ..."
rm -rf certs/ crl/ index.txt  newcerts/ private/ serial intermediate/

echo "  - Initializing directories and files ..."
mkdir certs crl newcerts private
chmod 700 private
touch index.txt
echo 1000 > serial

echo "  - Generating private key for root ca cert ..."
privkey="${MYDIR}/private/ca.key.pem"
openssl genrsa -out ${privkey} ${KEYSIZE}
chmod 400 ${privkey}


echo "  - Generating csr req for root ca cert ..."
rootcacert="${MYDIR}/certs/ca.cert.pem"
openssl req -config openssl.conf -key ${privkey} -new -x509 -days ${DAYS}  \
            -sha256 -extensions v3_ca -subj "${CASUBJECT}"  \
	    -out ${rootcacert}
chmod 444 ${rootcacert}

echo "  - Verify root ca cert"
openssl x509 -noout -text -in ${rootcacert} | head && echo "... "
